language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-24
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    
# Emulator Management: Create, Start and Wait
before_install:
  - yes | sdkmanager "platforms;android-27"
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-boot-anim -no-window &
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh

script:
  - android list target
# build app and assemble APK, in debug mode
  - ./gradlew assembleDebug
# install app, then assemble and install instrumented tests
  - ./gradlew installDebug
  - ./gradlew installDebugAndroidTest